# Generated by roxytest: Do not edit by hand!

context("File R/distribution.R: @testexamples")

test_that("Function gcap.plotDistribution() @ L30", {
  
  set.seed(1234)
  data <- data.frame(
    sample = sample(LETTERS[1:10], 100, replace = TRUE),
    class = sample(c("nofocal", "noncircular", "circular"), 100, replace = TRUE),
    by = sample(1:4, 100, replace = TRUE)
  )
  p <- gcap.plotDistribution(data)
  p
  expect_is(p, "ggplot")
})

